### ISSUE TITLE
Support (at least) utf-8 in literals and strings

### ISSUE THREAD

**Issue by Metaxal** [racket/rhombus#146]
I quite often use greek letters, math symbols and various brackets in identifiers and not having utf-8 support would be a huge bummer for me. 

Also, it's one of these 'small' features where I can very easily show off Racket to my friends, as it makes it look more advanced (and future-oriented) than most languages.

This has some support from #136 and [here](https://github.com/racket/rhombus-brainstorming/issues/145#issue-741987554).

**Comment by rocketnia** [comment]
Regarding brackets: What kind of policy do you imagine for letting brackets be used in identifiers? Would you like certain specific brackets to be identifier-friendly and others to be strictly for lexical structure? Would the same bracket be usable in different ways depending on context?

I find it to be an interesting topic. In the presence of Unicode, disallowing *all* brackets would probably just lead people to use bracket lookalike characters instead.

**Comment by Metaxal** [comment]
I think Racket's current setting is quite good.
Basically, allow everything in identifiers except (), [], {} and | | (except when used inside | |). The rule is simple and predictable.

Some brackets i've been using recently include 〈 〉  ⌊ ⌋  ⌈ ⌉ and <> as a lazy parenthesis replacement.

**Comment by slaymaker1907** [comment]
Just to add on to what @Metaxal said, apparently Racket handles identifiers containing | by just using a backslash to escape characters instead of the || syntax.

```rkt
(string->symbol "(42)") ;; outputs as '|(42)|
(string->symbol "|10 |10 ()") ;; outputs as '\|10\ \|10\ \(\)
```

It might be worth revisiting the format of the latter since that is really difficult to read IMO. Maybe just require \ to be escaped inside the || syntax in order to let you use \| for | in a symbol?

**Comment by Lazerbeak12345** [comment]
A few arguments in favor of this issue here: <https://utf8everywhere.org/>

In addition, such support could

- Maintain compatibility with libraries written for `#lang racket` without much mental overhead.
- Maintain the potential for something like `#lang español/racket` or `#lang español/rhombus` or something that would allow programmers to program in foreign languages, but with nearly the same surface syntax (Spanish isn't a great example, but the more complicated eastern languages would be a better example). - Something that in `#lang racket` is very easy, even if it hasn't been done yet. (I mean, why is it that most programming languages are still english-only nowdays? lol)

**Comment by countvajhula** [comment]
I noticed we can't define unicode operators, which seems related to this issue.

For example, this works:
```
operator n&:
  ~stronger_than: + - * /
  n * n

5& // => 25
```

but this doesn't:
```
operator n²:
  ~stronger_than: + - * /
  n * n

5² // different read error
```

The error from defining the `²` operator is:

```
; operator: expected more terms
;   at: [end of group]
;   within: operator n²:
;             ~stronger_than: + - * /
;             n * n
;   in: operator n²:
;         ~stronger_than: + - * /
;         n * n
;   parsing context: 
;    while parsing prefix operator case
;     term: (n² (block (group #:stronger_than (block (group...
;     location: scratch

```

**Comment by mflatt** [comment]
You can define Unicode symbol and punctuation combinations as operators in the current Rhombus prototype. The issue in the above example is that ² is numeric in Unicode, not symbolic or punctuation. So, `n²` is an identifier in the same way as `n2`, but `5²` is not a number, identifier, or operator.

**Comment by countvajhula** [comment]
I see, that makes sense 👍

**Comment by mflatt** [comment]
#527
