### ISSUE TITLE
Make an RFC for removing car and cdr (and probably cons)?

### ISSUE THREAD

**Issue by sorawee** [racket/rhombus#21]
We are not using IBM 704 anymore. Let's find a new name that makes more sense, and make students more relatable.

> Because of an unfortunate temporary lapse of inspiration, we couldn't think of any other names for the 2 pointers in a list node than "address" and "decrement", so we called the functions CAR for "Contents of Address of Register" and CDR for "Contents of Decrement of Register".
>
> After several months and giving a few classes in LISP, we realized that "first" and "rest" were better names, and we (John McCarthy, I and some of the rest of the AI Project) tried to get people to use them instead.
> 
> Alas, it was too late! We couldn't make it stick at all. So we have CAR and CDR.
> -- Steve Russell

**Comment by LiberalArtist** [comment]
I would support putting `first`, `rest`, and `empty` into the base language (vs. `racket/list`), but `first` and `rest` only work on proper lists, so they are different than `car` and `cdr`.

I could also see (but wouldn't necessarily advocate for myself) adding `pair` as an alias for `cons`, for symmetry with `pair?`, but I wouldn't remove `cons`, which is well-known in a way that `car` and `cdr` are not. Per [Wikipedia](https://en.wikipedia.org/wiki/Cons): 

> The word "cons" and expressions like "to cons onto" are also part of a more general functional programming jargon. Sometimes operators that have a similar purpose, especially in the context of list processing, are pronounced "cons". (A good example is the `::` operator in ML, Scala, F# and Elm or the `:` operator in Haskell, which adds an element to the beginning of a list.)

**Comment by jackfirth** [comment]
I've made two libraries in Rebellion that are related to this:

- [`rebellion/base/pair`](https://docs.racket-lang.org/rebellion/Pairs.html), which replaces normal racket pairs
- [`rebellion/collection/list`](https://docs.racket-lang.org/rebellion/Lists.html), which renames various racket list functions

Also, I don't think `cons` is a well-known name. It's somewhat well-known in functional programming, but it's completely unheard of outside that world.

**Comment by rocketnia** [comment]
IMO, using projection functions isn't as fun as using pattern-matching.

Starting from there, all that's left is what to call `cons`, and I don't know, and I've mostly just been using `cons`, even as part of the naming convention for other spine-shaped data structures. If I treated a list like it was just another one of those data structures, I'd probably call the constructors `list-coil-nil` and `list-coil-cons`. Other nice constructor names I might use for these are `list-coil-end`, `list-coil-empty`, and `list-coil-elem` (representing that this coil of the list contains one element, followed by further coils). "Coil" is a term I picked to represent one iteration of a recursive ADT's base functor, so that the coils could be said to "furl" and "unfurl" as data was collected and consumed.

**Comment by jeapostrophe** [comment]
I like `pair`, `fst`, and `snd`; as well as `tuple` and `\pi_i` for many `i`.

**Comment by emacsomancer** [comment]
As per @LiberalArtist 's suggestion, I like the idea of leaving `car`, `cdr`, `cons` for 'low-level' things, and having `first`, `rest` in the base language as only operating on lists (which might be familiar to users with Clojure experience).

**Comment by stamourv** [comment]
> first and rest only work on proper lists, so they are different than car and cdr.

IMO, that's an argument in favor of `first` and `rest`, and for taking out `car` and `cdr` (and making `cons` require its second argument to be a list). IME, improper lists are mainly the result of bugs, and a source of confusion.

**Comment by sorawee** [comment]
I think there are two separate issues:

1. Should _pair_ accessors/constructor be named `car` and `cdr` and `cons`? (the original topic)
2. Should list comprises of pairs? 

(2) seems to have three solutions: 
1. Yes, everything stays the same
2. Yes, but there should be another constructor the enforces the second argument to be a list (similar to Pyret's `link`).
3. No. 

See also https://groups.google.com/d/msg/racket-users/avZkchOzRS0/9CahqtIxEwAJ, a relevant discussion.

**Comment by AlexKnauth** [comment]
These two issues being combined together is confusing because `cons` means both "add to the beginning of a list" and "create a pair of two values" to different people. In my opinion those meanings should be separated from one another and `cons` should _only_ mean add to the beginning of a list, similar to how it's done in the teaching languages starting with Beginning Student Language.

  (1) For pairs, `pair` or `tuple` makes more sense as a constructor, and `fst` and `snd` or `tuple-0` and `tuple-1` make more sense as selectors.

  (2) For lists, I think `cons`, `first`, and `rest` make a good set together, as long as `cons` is separated from the "pair" meaning, changed to only deal with lists as in BSL through ISL+.

A side effect of making `cons` only for lists is that `list?` becomes an O(1) check instead of a potentially O(n) check

**Comment by sorawee** [comment]
The question is, should  `(pair 1 empty)` be a list?

If so, then I don't see how `list?` could become O(1)

**Comment by rocketnia** [comment]
At some point I thought I heard Racket made `list?` an O(1) check by storing a bit with each cons cell that meant "this cons cell is a proper list." Is that true? I might be thinking of another Lisp.

If that technique were used for mutable lists too, I guess it might make some operations more inefficient because they'd have to update all the parent cons cells.

Anyway, if this were an all-new language I'd be for having a `pair?` type that's distinct from a `list?` type, and I'd be against having improper lists. (In place of improper lists, I find it makes more sense to use a "partially folded list/partially unfolded stream" data type where there's an explicit constructor for the remainder... something like `(imlist-cons 1 (imlist-cons 2 (imlist-remainder "345"))`.)

In the context of the Racket ecosystem as it stands, making any big changes to what the terms "list" and "pair" mean might be tricky since existing packages use those terms in their documentation in ways that are important to understand how they can be used together in a larger program. Even if we add a new `list?` type and a new `pair?` type while preserving the legacy notions under different names, that means people have to think of `#lang racket` as one of the languages that uses legacy terminology. (Maybe that's inevitable?) And since Scheme's `lambda` syntax relies on improper lists to represent rest arguments, any move to actually *remove* improper lists would probably break the basic assumptions of many s-expression languages on the platform (including `#lang racket`), so I doubt that's worth it.

**Comment by mflatt** [comment]
#527
