### ISSUE TITLE
[Meta-issue] clarify how this repo works

### ISSUE THREAD

**Issue by sorawee** [racket/rhombus#43]
@jeapostrophe We have a lot of discussions in Github's Issues. Now what?

- When should one submit an RFC PR?
- Should discussion be on the PR or issues? 
- How are discussion on PR and issues different?
- How to keep discussion on PR and issues in sync?
- Could there be an RFC PR without an issue? 
- When does a PR get merged? Is that considered an approval?
- etc.

Github Issues also have labels. Can we make use of it to make organization easier?

**Comment by pmatos** [comment]
As far as I understand it @mflatt is working a proposal on how to move forward with regards to the racket2 contribution process. I have been reading on the sidelines wondering if I should voice my opinion now or give space so that Matthew and the leadership team voice how they would prefer to proceed.

Honestly I am not sure if starting creating RFC's etc, is going to help the process at all. I think the discussion is good but I wouldn't start creating formal RFCs just yet. This is based on my perception of the situation but you might, of course, have inside information that I don't.

**Comment by jeapostrophe** [comment]
I agree with @pmatos.

We're waiting for the major part of the plan. I think that the discussion so far is very productive and more focused than a similar discussion on the mailing list or via chat. We should continue it and shift things as the details are worked out.

**Comment by mflatt** [comment]
#527
