### ISSUE TITLE
Feature request: Map binding default value for absent key

### ISSUE THREAD

**Issue by AlexKnauth** [racket/rhombus#547]
Extend the Map binding to allow specifying a default value to match when the key is not in the Map.

Example:
```
let { "x": x = #false }: { "x": 0 }
//x ~is 0
let { "y": y = #false }: { "x": 0 }
//y ~is #false
```

**Comment by tgbugs** [comment]
Wouldn't this effectively create a type of map that contains every possible key? This produces inconsistent behavior because `List.find([key, ...], fun(x): x == "key") -> #false` but `my_map["key"] -> 0` or any other non `#false` value that was provided as the default. One option might be to have such maps have a different type (subtype?) but that seems fraught to me. Another solution that would maintain consistent behavior would be to allow `my_map["key" ~default: = #false]` at lookup time so that instead of raising a key error the specified value would be returned at the call site (maybe it already does this?).

**Comment by usaoc** [comment]
For those who are new to Racket/Rhombus: `map[key]` and `map.get(key)` desugar to `(hash-ref map key)`, which throws if the `key` isn’t in the `map`.  To supply a default value, you can use `map.get(key, default_val)`, which desugars to `(hash-ref map key default_val)`.  We don’t force a default value, because a map can in principle contain any value (even the special `unsafe-undefined` value, although that can break code that treats that as “not found”).

The issue is about extending the binding (pattern) form for matching a map with optional keys.
