### ISSUE TITLE
Philosophy proposal: reserve generic names for generic behavior

### ISSUE THREAD

**Issue by jackfirth** [racket/rhombus#80]
This is a bit of a meta-issue, related to #35, #19, #49, and #21.

There's a lot of discussion related to generics in Racket2. I think we need to decide on a guiding philosophy for our goals in this area, as a way of focusing our efforts and keeping us consistent. My proposal for such a philosophy is this: **generic names should be reserved for generic behavior**.

Note that "generic behavior" does not necessarily mean "methods on a generic interface": any means of abstracting over implementation details will do. More concretely, we can imagine an equation relating how generic a name is to how many situations the named behavior is useful for:

```
genericness of name / number of use cases = constant
```

The more generic a name is—meaning, the fewer details it prescribes about the behavior being named—then the more use cases the named functionality should address. When a name fails to uphold this principle, such as the various list-specific `map`, `filter`, and `fold` functions, then we are forced to use more complex names for the equivalent generic behavior such as `sequence-map`, `sequence-filter`, and `sequence-fold`.

Rather than leading users to write longer names in code, this causes users to *avoid the generic names entirely* and artificially restrict the set of problems their code can solve. So the specialized behavior of `map`, `filter`, and `fold` is not merely a tax on our namespace, but on our *problem space* as well.

I think we should evaluate naming decisions for all Racket2 APIs—not just the collection and sequence related ones—through this lens. Whenever new names are proposed, and whenever we have the opportunity to change existing names, we should consider whether the name is specific enough or generic enough for the scope of problems it's meant to address.

**Comment by jeapostrophe** [comment]
I agree

**Comment by rocketnia** [comment]
Any given operation has many ways it can be made generic, and as you can see on #84, I have a few different ones in mind for most operations. Each possible choice tends to be best suited by a different specific name; otherwise one of the names looks like it can do everything the others do, and that's a little misleading.

Sure, the language core has a relatively unique opportunity to make bold naming choices that take this kind of risk, but I'm not optimistic to see a whole ecosystem full of terse names. And since I think a library ecosystem tends to try to conform with the language core, and a language core tends to become just another library when someday a new extensible language core is built underneath it, I think the core has a certain responsibility to use names that set a good example to help everyone interoperate with each other.

But it's probably obvious enough that libraries that make *whole new languages* can afford to be bolder about their naming conventions than libraries that define a few new utilities. And if it's ever really a problem, people can use `rename-in` or `prefix-in`. So it seems fine. :)

**Comment by mflatt** [comment]
#527
